name: Frontend CI/CD

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
  IMAGE_NAME: eschool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install deps
        run: |
          npm install -g @angular/cli@7
          yarn install --frozen-lockfile

      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=eschool-frontend-final-project
            -Dsonar.sources=src


  docker-build-and-push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "$DOCKER_PAT" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build image
        run: |
          docker build \
            -t $DOCKER_USERNAME/$IMAGE_NAME:frontend-${GITHUB_RUN_NUMBER} \
            -t $DOCKER_USERNAME/$IMAGE_NAME:frontend-latest \
            .

      - name: Push image
        run: |
          docker push $DOCKER_USERNAME/$IMAGE_NAME:frontend-${GITHUB_RUN_NUMBER}
          docker push $DOCKER_USERNAME/$IMAGE_NAME:frontend-latest


deploy:
  name: Deploy Frontend
  runs-on: ubuntu-latest
  on:
    push:
      branches: [main]

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SSH and deploy
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        IMAGE_NAME: eschool
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.SERVER_IP }} <<EOF
          export DOCKER_USERNAME=$DOCKER_USERNAME
          export DOCKER_PAT=$DOCKER_PAT
          export IMAGE_NAME=$IMAGE_NAME

          echo "$DOCKER_PAT" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker pull $DOCKER_USERNAME/$IMAGE_NAME:frontend-latest
          docker compose up -d --force-recreate frontend
EOF

        rm -f private_key.pem
